export enum AuthorRole {
  /**
   * A system message helps set the behavior of the assistant.
   */
  SYSTEM = "system",
  /**
   * An assistant message is a message generated by the assistant.
   */
  ASSISTANT = "assistant",
  /**
   * A user message is a message generated by the user.
   */
  USER = "user",

  /**
   * A tool message is a message generated by a tool.
   */
  TOOL = "tool",

  MODEL = "model",
}

export const authorRoleFromString = (name: string): AuthorRole => {
  switch (name) {
    case "user":
      return AuthorRole.USER
    case "system":
      return AuthorRole.SYSTEM
    case "assistant":
      return AuthorRole.ASSISTANT
    case "tool":
      return AuthorRole.TOOL
    case "model":
      return AuthorRole.MODEL
    default:
      throw new Error("unrecognized author role")
  }
}
