export enum AuthorRole {
  /**
   * A system message helps set the behavior of the assistant.
   */
  SYSTEM = "system",
  /**
   * An assistant message is a message generated by the assistant.
   */
  ASSISTANT = "assistant",
  /**
   * A user message is a message generated by the user.
   */
  USER = "user",

  /**
   * A tool message is a message generated by a tool.
   */
  TOOL = "tool",
}
